# Generated by Django 4.1.1 on 2022-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodels',
            name='children_image',
            field=models.ImageField(help_text='children_image', null=True, upload_to='images/user'),
        ),
    ]
