# Generated by Django 4.1.1 on 2022-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_childmodels_url_alter_childmodels_children_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
        migrations.RemoveField(
            model_name='childmodels',
            name='url',
        ),
    ]
