# Generated by Django 4.1.4 on 2022-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_childmodels_children_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childmodels',
            old_name='children_status',
            new_name='children_status1',
        ),
        migrations.AddField(
            model_name='childmodels',
            name='children_status2',
            field=models.CharField(default='pending', help_text='children_status', max_length=50),
        ),
    ]
