# Generated by Django 4.1.4 on 2022-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_children_status_childmodels_children_status1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_status', models.TextField(help_text='delay_status')),
            ],
            options={
                'db_table': 'bus_delay_details',
            },
        ),
    ]
